yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: "Evaluation of the retrieval system"
prompts:
  - "{{ query }}"

providers:
  - file://provider.ts

tests:
  - vars:
      query: What's the example used in the MDN docs to demonstrate how to declare a variable?
    assert:
      - type: contains-all
        value:
          - mdn-js-docs/grammar_and_types/index.md-chunk_8
          - mdn-js-docs/expressions_and_operators/index.md-chunk_1
